[package]
name = "dioxus-primitives"
version = "0.0.1"
edition = "2021"
rust-version = "1.80.0"
readme = "../README.md"
keywords = ["gui", "dioxus", "components", "primitives"]
categories = ["gui", "wasm"]
authors = ["Dioxus Labs", "DogeDark"]
license = "MIT OR Apache-2.0"
homepage = "https://dioxuslabs.com"
repository = "https://github.com/DioxusLabs/components"

[dependencies]
dioxus.workspace = true
dioxus-core.workspace = true
dioxus-attributes = { path = "../dioxus-attributes" }
time = { version = "0.3.44", features = ["std", "macros", "parsing", "local-offset"] }
num-integer = "0.1.46"
tracing.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
palette = "0.7.6"
wasm-bindgen = { version = "0.2.122-alpha.5", package = "wasm-bindgen-x" }
js-sys = { version = "0.3.99-alpha.5", package = "js-sys-x" }
wasm-bindgen-futures = { version = "0.4.72-alpha.5", package = "wasm-bindgen-futures-x" }
web-sys = { version = "0.3.99-alpha.5", package = "web-sys-x", features = [
    "AddEventListenerOptions",
    "Window",
    "Document",
    "Element",
    "Event",
    "HtmlElement",
    "HtmlHeadElement",
    "HtmlImageElement",
    "HtmlInputElement",
    "HtmlBodyElement",
    "CssStyleDeclaration",
    "EventTarget",
    "KeyboardEvent",
    "PointerEvent",
    "Node",
    "DragEvent",
    "DataTransfer",
    "VisualViewport",
    "Navigator",
] }

[build-dependencies]
lazy-js-bundle = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.52.3", features = ["time"] }

[dev-dependencies]
dioxus-ssr = { workspace = true }

[features]
default = ["router"]
router = ["dioxus/router"]
web = ["time/wasm-bindgen"]
