[package]
name = "wry-bindgen-event-reentry-mre"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "be7bc4683a77b2e8a7c1945fd17f6f7f91af28d0", features = ["desktop"] }
js-sys = { version = "0.3.83-alpha.1", package = "js-sys-x" }
wasm-bindgen = { version = "0.2.106-alpha.1", package = "wasm-bindgen-x" }
web-sys = { version = "0.3.83-alpha.1", package = "web-sys-x", features = [
    "Event",
] }

[patch.crates-io]
wry-bindgen = { path = "/Users/evanalmloff/Desktop/wasm-bindgen-wry/wry-bindgen" }
wry-bindgen-macro = { path = "/Users/evanalmloff/Desktop/wasm-bindgen-wry/wry-bindgen-macro" }
wry-bindgen-macro-support = { path = "/Users/evanalmloff/Desktop/wasm-bindgen-wry/wry-bindgen-macro-support" }
